name: First workflow

on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        php-versions: ['7.2', '7.3', '7.4']

    name: ${{ matrix.os }} PHP ${{ matrix.php-versions    }}

    steps:
      - uses: actions/checkout@v2

      - name: Hello World! 
        run: echo "Hello! from ${{ github.workflow }} triggered by the ${{ github.event_name }} done by ${{ github.actor }}"
        
      - name: 🌸 More and more
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: |
          echo "Job Context: $JOB_CONTEXT"
          echo "Done!"
      
      - name: Greeting if Windows
        if: matrix.os == 'windows-latest'
        run: echo "Hey from Win2!"

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: Install dependencies
        working-directory: ./lessons/03-continuous_Integration/03.1-Executing_tests
        run: composer install --ignore-platform-reqs

      - name: Run the tests
        working-directory: ./lessons/03-continuous_Integration/03.1-Executing_tests
        run: composer phpunit
